name: Release

on:
  release:
    types: [ published ]

jobs:
  release_server:
    name: Build binary (Linux amd64)
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GO111MODULE: on
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      env:
        RUNNER_TEMP: /tmp
      uses: actions/setup-go@v2
      with:
        go-version: ^1.20
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run tests
      run: go test -v ./...

    - name: Build binary
      run: go build -o subgrok ./cmd/subgrok/main.go

    - name: Make binary executable
      run: chmod +x subgrok*

    - name: Attach binary to release
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: subgrok*
